title: "ExplainMath"
description: "A Python library that prevents silent numeric failures."
theme: "just-the-docs"

# Navigation
nav_order: 1

just_the_docs:
  search_enabled: true
  heading_anchors: true
