title: "ExplainMath"
description: "A Python library that prevents silent numeric failures."
theme: jekyll-theme-cayman
markdown: kramdown

# Enable ordering for sidebar navigation
nav_order: 1
